# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Configure VM
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  # Specify the Vagrant box to build on
  config.vm.box = "ubuntu/xenial64"

  # Specify bootstrapping
  config.vm.provision :shell, path: "scripts/base-provision.sh", privileged: false

  # HTTP port
  config.vm.network :forwarded_port, host: 4200, guest: 4200

end
