# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Ember port
  config.vm.network :forwarded_port, host: 4200, guest: 4200

  # Ember live reload port
  config.vm.network :forwarded_port, host: 35729, guest: 35729



  # The development box builds on the base box
  config.vm.define "dev" do |dev|
    
    # Specify the Vagrant box to build on
    dev.vm.box = "geenpeil-base-1.box"
    dev.vm.box_url = "geenpeil-base-1.box"

    # Specify bootstrappings
    dev.vm.provision :shell, path: "scripts/dev-provision.sh", privileged: false

    # Configure VM hardware usage
    config.vm.provider "virtualbox" do |v|
      v.memory = 512
    end

  end

  # The base box with all the required software installed
  config.vm.define "base" do |base|

    # Specify the Vagrant box to build on
    base.vm.box = "ubuntu/trusty64"

    # Specify bootstrappings
    base.vm.provision :shell, path: "scripts/base-provision.sh", privileged: false

    # Configure VM hardware usage
    config.vm.provider "virtualbox" do |v|
      # minimum 1024MB RAM 
      v.memory = 1024
      # consider increasing cpu count
      v.cpus = 1
    end

  end

end
