// Code generated by protoc-gen-go.
// source: gph.proto
// DO NOT EDIT!

/*
Package data is a generated protocol buffer package.

It is generated from these files:
	gph.proto

It has these top-level messages:
	GPH
*/
package data

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type GPH struct {
	RSAEncryptedAESKey []byte `protobuf:"bytes,1,opt,proto3" json:"RSAEncryptedAESKey,omitempty"`
	AESEncryptedData   []byte `protobuf:"bytes,2,opt,proto3" json:"AESEncryptedData,omitempty"`
}

func (m *GPH) Reset()         { *m = GPH{} }
func (m *GPH) String() string { return proto.CompactTextString(m) }
func (*GPH) ProtoMessage()    {}

func init() {
}
